- hosts: all
  tasks: 
  # Configure Kubernetes Resource  
  - name: Create "demospace" namespace
  community.kubernetes.k8s:
    name: demospace
    api_version: v1
    kind: Namespace
    state: present
