- hosts: all
  roles:
  - role: ansible.kubernetes-modules
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
