- hosts: all
  collections:
    - kubernetes.core.k8s
  tasks:
  - name: Create a namespace
    kubernetes.core.k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present
