- hosts: all
  tasks:
  - name: echo Message
    command: echo "Log into ${clsuter_name} cluster"
    
  - name: Login to Openshift
    command: echo "oc login -t ${cluster_authtoken}"

  - name: Create a namespace
    command: /usr/local/bin/oc create namespace ${namespace_name}"
