- hosts: all

  tasks:
  - name: Login to Openshift
    command: echo "Log into {{ cluster_name }} cluster" >> /tmp/test.log
    command: echo "oc login -t {{ cluster_authtoken }}" >> /tmp/test.log

  - name: Create a namespace
    command: /usr/local/bin/oc create namespace {{ namespace_name }}
