- hosts: all

  tasks:
  - name: Login to Openshift
    message: "Log into {{ cluster_name }} cluster"
    command: echo "oc login -t {{ cluster_authtoken }}"

  - name: Create a namespace
    command: /usr/local/bin/oc create namespace {{ namespace_name }}
