- hosts: all
  tasks:
  - name: Refresh package lastet
    copy:
      dest: "/home/ibmuser/rba-result.txt"
      content: |
        Successfully started Online Banking Application using Ansible playbook and Runbook automation!
