- hosts: all

  tasks:
  - name: Login to Openshift
    command: echo "Log into {{ cluster_name }} cluster" >> /tmp/test.log
    command: oc login --token={{ cluster_authtoken }} --server=https://{{ api_server_host }}:{{ api_server_port }}

  - name: Set Quota to the namespace
    command: /usr/local/bin/oc create -n {{ namespace_name }} quota bigblue-quota --hard=cpu={{ cpu_hard_limit }},memory={{ memory_hard_limit }}
