apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sample-networkpolicy
  namespace: securens
spec:
  podSelector:
    matchLabels:
      role: securedb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: allowedap
  policyTypes:
  - Ingress
