apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
namespace: private
metadata:
  name: default-deny-ingress
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: allowedap
  policyTypes:
  - Ingress
